version: "3.9"
services:
  mysql_service:
    container_name: mysql_server
    build: ./mysql
    restart: always
    ports:
      - "6603:3306"
    networks:
      mynet:
        ipv4_address: 6.6.0.4
    
  mysql_api:
    container_name: api
    build: ./mysql_api
    ports:
      - "9000:8000"
    volumes:
      - ./web_page/static:/api/static
      - ./web_page/templates:/api/templates
    networks:
      mynet:
        ipv4_address: 6.6.0.6


networks:
  mynet:
    driver: bridge
    ipam:
     config:
       - subnet: 6.6.0.0/16